[package]
name = "naga"
version = "0.8.0"
authors = ["Naga Developers"]
edition = "2018"
description = "Shader translation infrastructure"
homepage = "https://github.com/gfx-rs/naga"
repository = "https://github.com/gfx-rs/naga/tree/v0.8"
keywords = ["shader", "SPIR-V", "GLSL", "MSL"]
license = "MIT OR Apache-2.0"
exclude = ["bin/**/*", "tests/**/*", "Cargo.lock", "target/**/*"]
resolver = "2"

[package.metadata.docs.rs]
all-features = true

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[features]
default = []
dot-out = []
glsl-in = ["pp-rs"]
glsl-validate = []
glsl-out = []
msl-out = []
serialize = ["serde", "indexmap/serde-1"]
deserialize = ["serde", "indexmap/serde-1"]
spv-in = ["petgraph", "spirv"]
spv-out = ["spirv"]
wgsl-in = ["codespan-reporting", "hexf-parse"]
wgsl-out = []
hlsl-out = []
span = ["codespan-reporting"]
validate = []

[[bench]]
name = "criterion"
harness = false

# MSRV warnings:
# - arbitrary 1.0.3 requires Rust-1.51
# - bitflags 1.3 requires Rust-1.46
# - indexmap 1.7 requires Rust-1.49

[dependencies]
arbitrary = { version = "1", features = ["derive"], optional = true }
bitflags = "1"
bit-set = "0.5"
codespan-reporting = { version = "0.11.0", optional = true }
rustc-hash = "1.1.0"
indexmap = "1.6"
log = "0.4"
num-traits = "0.2"
spirv = { version = "0.2", optional = true }
thiserror = "1.0.21"
serde = { version = "1.0", features = ["derive"], optional = true }
petgraph = { version ="0.6", optional = true }
pp-rs = { version = "0.2.1", optional = true }
hexf-parse = { version = "0.2.1", optional = true }

[dev-dependencies]
bincode = "1"
criterion = { version = "0.3", features = [] }
diff = "0.1"
ron = "0.7"
serde = { version = "1.0", features = ["derive"] }
spirv = { version = "0.2", features = ["deserialize"] }
rspirv = "0.11"
env_logger = "0.9"

[workspace]
members = [".", "cli"]

# Include "cli", so that `cargo run` runs the CLI by default. Include ".", so
# that `cargo test` includes naga's own tests by default (but note, using the
# features that `cli/Cargo.toml` requests).
default-members = [".", "cli"]
