name: validation-macos
on:
  pull_request:
    paths:
      - '.github/workflows/validation-macos.yml'
      - 'tests/out/msl/*.msl'

jobs:
  validate-macos:
    name: MSL
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - run: make validate-msl
